defmodule SoundForge.DJ.PerformanceSet do
  @moduledoc """
  Unified schema for AI-generated and manually-created performance sets.

  Replaces ChefSet / AlchemySet / Recipe with a single, schema-driven type.
  Items are stored as a JSONB array — no separate table needed.

  ## Set Types
    - `:cueset`   — cue point markers (hot cues, memory cues)
    - `:loopset`  — loop regions (auto loops, manual loops)
    - `:stemset`  — per-stem volume/mute configurations
    - `:hybrid`   — mix of cues, loops, and stem configs

  ## Sources
    - `:chef`     — generated by the AI Chef worker
    - `:manual`   — saved manually from the DJ editor
    - `:imported` — imported from an external format

  ## Item Structure (stored in `items` JSONB array)
    Each item is a map with:
      - `"position_ms"` — start position in ms
      - `"end_ms"` — end position (loops / regions only)
      - `"label"` — human-readable label
      - `"item_type"` — "cue" | "loop" | "stem" | "marker"
      - `"color"` — hex color for UI rendering
      - `"sort_order"` — integer sort key
      - `"loop_start_ms"` / `"loop_end_ms"` — for loops
      - `"stem_config"` — map of stem names to volume/mute
      - `"confidence"` — float 0–1 (for AI-generated items)
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  @set_types ~w(cueset loopset stemset hybrid)
  @sources ~w(chef manual imported)

  schema "performance_sets" do
    field :name, :string
    field :set_type, :string, default: "cueset"
    field :source, :string, default: "chef"
    field :schema_version, :string, default: "1.0"
    field :items, {:array, :map}, default: []
    field :metadata, :map, default: %{}
    field :activated_at, :utc_datetime
    field :generation_opts, :map, default: %{}

    belongs_to :user, SoundForge.Accounts.User, type: :integer, foreign_key: :user_id
    belongs_to :track, SoundForge.Music.Track, type: :binary_id, foreign_key: :track_id

    timestamps()
  end

  @type t :: %__MODULE__{}

  @spec changeset(t(), map()) :: Ecto.Changeset.t()
  def changeset(%__MODULE__{} = set, attrs) do
    set
    |> cast(attrs, [
      :name,
      :set_type,
      :source,
      :schema_version,
      :items,
      :metadata,
      :activated_at,
      :generation_opts,
      :user_id,
      :track_id
    ])
    |> validate_required([:name, :set_type, :source, :user_id])
    |> validate_inclusion(:set_type, @set_types)
    |> validate_inclusion(:source, @sources)
    |> validate_length(:name, min: 1, max: 200)
  end

  @doc """
  Returns a JSON Schema map describing the PerformanceSet structure,
  suitable for use as an LLM output constraint.
  """
  @spec json_schema() :: map()
  def json_schema do
    %{
      "type" => "object",
      "required" => ["name", "set_type", "source", "items"],
      "properties" => %{
        "name" => %{"type" => "string", "maxLength" => 200},
        "set_type" => %{"type" => "string", "enum" => @set_types},
        "source" => %{"type" => "string", "enum" => @sources},
        "schema_version" => %{"type" => "string"},
        "items" => %{
          "type" => "array",
          "items" => %{
            "type" => "object",
            "required" => ["position_ms", "label", "item_type"],
            "properties" => %{
              "position_ms" => %{"type" => "integer", "minimum" => 0},
              "end_ms" => %{"type" => "integer", "minimum" => 0},
              "label" => %{"type" => "string"},
              "item_type" => %{"type" => "string", "enum" => ["cue", "loop", "stem", "marker"]},
              "color" => %{"type" => "string"},
              "sort_order" => %{"type" => "integer"},
              "loop_start_ms" => %{"type" => "integer"},
              "loop_end_ms" => %{"type" => "integer"},
              "stem_config" => %{"type" => "object"},
              "confidence" => %{"type" => "number", "minimum" => 0, "maximum" => 1}
            }
          }
        },
        "metadata" => %{"type" => "object"},
        "generation_opts" => %{"type" => "object"}
      }
    }
  end
end
